### ISSUE TITLE
Cannot install package on Windows

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/mati-reactnative-plugin#46]
Following the provided [documentation](https://docs.getmati.com/docs/react-native), when I run `npm i https://github.com/MatiFace/react-native-mati-global-id-sdk.git --save` I get the following error:

```bash
npm ERR! npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! C:\Users\elbom\AppData\Local\npm-cache\_cacache\tmp\git-cloneV8irTY\node_modules\expo-module-scripts\bin\expo-module-prepare:3
npm ERR! set -eo pipefail
npm ERR!         ^^^^^^^^
npm ERR!
npm ERR! SyntaxError: Unexpected identifier
npm ERR!     at Object.compileFunction (node:vm:352:18)
```

I have tried with yarn as well, our preferred package manager.

If I use command `npm i react-native-metamap-sdk`, it installs this version:
```json
    "react-native-metamap-sdk": "^1.0.18",
```

While I need the latest v4.0.0

```
System:
    OS: Windows 10 10.0.22581
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 11.20 GB / 31.86 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\.yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14.1 - /c/Program Files/Microsoft/jdk-11.0.14.101-hotspot/bin/javac
  npmPackages:
    @react-native-community/cli: 7.0.3 => 7.0.3
    react: 18.0.0 => 18.0.0
    react-native: 0.68.0 => 0.68.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by bombillazo** [comment]
👀 @MikeApp-0103

**Comment by AvoSukiasyan** [comment]
@bombillazo "react-native-metamap-sdk": "^1.0.18", it's latest React Native Expo version

**Comment by AvoSukiasyan** [comment]
for install - `npm install https://github.com/MatiFace/react-native-mati-global-id-sdk.git --save`
on document wrote both RN and Expo.


React Native implementation is `

import React, {Component} from 'react';
import {
  NativeModules,
  NativeEventEmitter,
  Button,
  View
} from 'react-native';

import {
  MetaMapRNSdk,
} from 'react-native-metamap-sdk';

export default class App extends Component {
  constructor() {
    super();
    console.log('Constructor Called.');
  }

  componentDidMount() {
	 //set listening callbacks
  	const MetaMapVerifyResult = new NativeEventEmitter(NativeModules.MetaMapRNSdk)
 	 MetaMapVerifyResult.addListener('verificationSuccess', (data) => console.log(data))
 	 MetaMapVerifyResult.addListener('verificationCanceled', (data) => console.log(data))
  }

  //call showFlow when button is clicked
  handleMetaMapClickButton = () => {

	 //set 3 params clientId (cant be null), flowId, metadata
  	  var yourMetadata = { param1: "value1", param2: "value2" }

   	 MetaMapRNSdk.showFlow("YOUR_CLIENT_ID", "YOUR_FLOW_ID", yourMetadata);
  }

  //Add button to view graph
  render() {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: 'powderblue',
        }}>
        <Button onPress={this.handleMetaMapClickButton} title="Click here"/>
      </View>
    );
  }
}

**Comment by bombillazo** [comment]
Ok, when I use that install command, this is the error I get:

```bash
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\elbom\AppData\Roaming\nvm\v16.14.2\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\elbom\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > react-native-metamap-sdk@4.0.2 prepare
npm ERR! > expo-module prepare
npm ERR! npm WARN using --force Recommended protections disabled.
...
npm ERR! npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! C:\Users\elbom\AppData\Local\npm-cache\_cacache\tmp\git-cloneWOGfI1\node_modules\expo-module-scripts\bin\expo-module-prepare:3
npm ERR! set -eo pipefail
npm ERR!         ^^^^^^^^
npm ERR!
npm ERR! SyntaxError: Unexpected identifier
npm ERR!     at Object.compileFunction (node:vm:352:18)
npm ERR!     at wrapSafe (node:internal/modules/cjs/loader:1032:15)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1067:27)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\elbom\AppData\Local\npm-cache\_cacache\tmp\git-cloneWOGfI1
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c expo-module prepare
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\elbom\AppData\Local\npm-cache\_logs\2022-04-06T14_50_48_610Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\elbom\AppData\Local\npm-cache\_logs\2022-04-06T14_48_10_570Z-debug-0.log
```

**Comment by AvoSukiasyan** [comment]
before install plugin you can try 
npm clean-install

or 
npm cache clean --force
npm install -g @angular/cli@latest

**Comment by bombillazo** [comment]
I tried both, still the same error.

**Comment by bombillazo** [comment]
I do not have a Mac, unfortunately.

I also tried installing it with `npm install react-native-mati-global-id-sdk` but it installs a lower version:

```
"react-native-mati-global-id-sdk": "^3.5.3",
```

But it does install something. it is version 4.0.0 that is giving trouble.

**Comment by AvoSukiasyan** [comment]
no, the correct path is npm install `https://github.com/MatiFace/react-native-mati-global-id-sdk.git --save`.
ok , got it,  in that case, we will check on the Windows tomorrow and get back to you

**Comment by bombillazo** [comment]
Thank you, I will be looking forward to this.

**Comment by bombillazo** [comment]
Hello, @AvoSukiasyan , I was able to get a Mac and test it, and yes it works as expected on Mac.

**Comment by greyes-developer** [comment]
Hello, I have the same error on Windows, like @bombillazo says, but I'm not able to get a Mac, however, other friends tried to install this package on their mac and they were success

**Comment by AvoSukiasyan** [comment]
Hi @greyes-developer .yeah it's a known issue already. we work to solve this issue.

**Comment by aposnovmati** [comment]
Hello @bombillazo we have just updated our documentation please try it, we had tested it on windows 11 and it works.
https://github.com/GetMetaMap/mati-reactnative-plugin
In a terminal, use the following command to install MetaMap for React Native:
**npm i react-native-metamap-sdk**

**Comment by bombillazo** [comment]
Working on it to confirm the issue is resolved, thanks!

**Comment by bombillazo** [comment]
Hello again, im glad to say the build now works! However, Im getting this error when I try to set the button text and color:
![image](https://user-images.githubusercontent.com/44002321/163871273-914f0b15-93ea-4b56-a733-d5758785e4ba.png)

This is the data I am passing:

```
const metadata = {
      buttonColor: '#FFC300',
      buttonTextColor: '#FD35AE73',
    };
```

**Comment by bombillazo** [comment]
I believe the issue lies here:

![image](https://user-images.githubusercontent.com/44002321/163874286-1b2ef19f-172c-4f29-83fd-e1f3225be4e9.png)

Casting directly to int doesn't seem to work, you'll need to use some utility function to parse into the @ColorInt type: 

https://stackoverflow.com/a/5248608/623770
https://stackoverflow.com/a/14533352/623770

By default that doesn't handle shortform hex colors (eg `#fff`) but some comments talk about how to do so.

**Comment by AvoSukiasyan** [comment]
Hello @bombillazo. while I check android. can you clarify please. for iOS work as expected for you?

**Comment by AvoSukiasyan** [comment]
looks like it's happening only on android (iOS works as expected) and you are right,  the issue is related to the parts of color.

**Comment by AvoSukiasyan** [comment]
Hi @bombillazo. I fixed the issue on the android. please update the plugin to the last version. 4.0.17

**Comment by bombillazo** [comment]
Its working! I believe I can close this issue now. :)
