### ISSUE TITLE
[Bug] Custom colors/apha leaking to Exit button

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/mati-reactnative-plugin#48]
At the moment when setting a custom text color, the exit button text color also changes:

![image](https://user-images.githubusercontent.com/44002321/164025644-b0833d4d-8d96-4f62-bf61-c4c3b3508d74.png)

My expectation would be the color remains white.

Platform: Android

**Comment by bombillazo** [comment]
Yes on Android

**Comment by bombillazo** [comment]
Also the exit button is taking the Alpha value from the color passed in the `buttonColor` parameter and changing the alpha of the exit button:
```
const metadata = {
      buttonColor: '#22000000', //AARRGGBB        
    };
```

Result:
![image](https://user-images.githubusercontent.com/44002321/164037980-2ba4783c-5bed-4c23-a194-04a977405e76.png)

**Comment by AvoSukiasyan** [comment]
Hi @bombillazo. please update the plugin to the last 4.0.19 version. 
Guys from the android team fixed the issue on the exit button.

**Comment by AvoSukiasyan** [comment]
@bombillazo is this problem solved for you?

**Comment by bombillazo** [comment]
Yes this is fixed! Thank you!
