### ISSUE TITLE
[Request] Match UI color to primary button color

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/mati-reactnative-plugin#49]
As a request, it would be great if the coloring for the flow UI matches the color of the button (or have its own color property).

Now:
![image](https://user-images.githubusercontent.com/44002321/164032688-8e776c5d-520a-49dd-8104-ad922596246b.png)

After:
![image](https://user-images.githubusercontent.com/44002321/164032506-79a77071-4a57-4789-8623-16d4ddcc83f1.png)

**Comment by AvoSukiasyan** [comment]
Yeah)) in the future we are going to do it, but so far it is only under discussion
