### ISSUE TITLE
[Bug] iOS RGBA color alpha (transparency) not working on button color

### ISSUE THREAD

**Issue by bombillazo** [GetMetaMap/mati-reactnative-plugin#51]
The alpha values in iOS button color are not working so transparency is not possible.
Tert color:
```js
const metadata = {
  buttonColor: '#AAAAAA11', //RRGGBBAA
};
```
Current:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/44002321/165161960-128d10a4-782e-4dc5-b91e-7bd44582a50a.png">

Expected:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/44002321/165162055-4be9ae50-816f-4dc0-810f-66ba81dbceee.png">

**Comment by AvoSukiasyan** [comment]
Hi @bombillazo.
I tested iOS many times and couldn't reproduce this case. for me the alpha of the button shows as expected.
can you tell me the details, maybe I did something different than you!

```
 const metadata = {
            buttonColor: '#AAAAAA11',
            buttonTextColor: '#FF1111',
          };

```
<img width="316" alt="Screen Shot 2022-04-28 at 12 33 21" src="https://user-images.githubusercontent.com/43985438/165711918-4e99fa75-2afd-4766-b11b-5820992229a3.png">
