### ISSUE TITLE
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

### ISSUE THREAD

**Issue by orjiAce** [GetMetaMap/mati-reactnative-plugin#63]
I get this error when I integrate the Meta map mobile SDK on my expo app
I'm using Expo SDK 45

<img width="568" alt="Screen Shot 2022-07-31 at 02 53 36" src="https://user-images.githubusercontent.com/29933392/182006282-8f4db50a-cbe9-4d0e-87af-7ac33a442172.png">
Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

**Comment by AvoSukiasyan** [comment]
hi @orjiAce.  can I have your package file? please

**Comment by AvoSukiasyan** [comment]
cc: @orjiAce
